resources:
- https://github.com/argoproj/argo-cd/manifests/crds?ref=stable
- https://github.com/argoproj/argo-cd/manifests/base/config?ref=stable
- https://github.com/argoproj/argo-cd/manifests/base/dex?ref=stable
- https://github.com/argoproj/argo-cd/manifests/base/redis?ref=stable
- https://github.com/argoproj/argo-cd/manifests/base/repo-server?ref=stable
- https://github.com/argoproj/argo-cd/manifests/base/server?ref=stable
- https://github.com/argoproj/argo-cd/manifests/cluster-rbac/server?ref=stable
- https://github.com/argoproj/argo-cd/examples/k8s-rbac/argocd-server-applications?ref=stable

patches:
- path: argocd-cmd-params-cm.yaml
- path: argocd-secret.yaml
- path: server-service.yaml
- path: repo-server-service.yaml
- path: redis-service.yaml
