resources:
- agent-sa.yaml
- agent-role.yaml
- agent-clusterrole.yaml
- agent-rolebinding.yaml
- agent-clusterrolebinding.yaml
- agent-deployment.yaml
- agent-params-cm.yaml
- agent-metrics-service.yaml
- agent-healthz-service.yaml

images:
- name: argocd-agent
  newName: quay.io/argoprojlabs/argocd-agent
  newTag: v0.5.4
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
